# Generated by Django 4.2.20 on 2025-05-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('dno', models.IntegerField(db_column='Dno', primary_key=True, serialize=False)),
                ('dname', models.CharField(db_column='Dname', max_length=100)),
                ('noofemp', models.IntegerField(db_column='NoOfEmp', null=True)),
                ('dlocation', models.CharField(db_column='Dlocation', max_length=100)),
            ],
            options={
                'db_table': 'departments',
                'managed': False,
            },
        ),
    ]
