# Generated by Django 4.2.20 on 2025-05-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeEducation',
            fields=[
                ('id', models.IntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('degree', models.CharField(db_column='Degree', max_length=255)),
                ('educationlevel', models.CharField(db_column='EducationLevel', max_length=50)),
                ('university', models.CharField(db_column='University', max_length=255)),
                ('startedyear', models.IntegerField(db_column='StartedYear', null=True)),
                ('status', models.CharField(db_column='Status', max_length=50)),
                ('completedyear', models.IntegerField(db_column='CompletedYear', null=True)),
            ],
            options={
                'db_table': 'employeeeducation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeEmails',
            fields=[
                ('emailtype', models.CharField(db_column='EmailType', max_length=50)),
                ('email', models.CharField(db_column='Email', max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'employeeemails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeePhones',
            fields=[
                ('phonetype', models.CharField(db_column='PhoneType', max_length=50)),
                ('phoneno', models.CharField(db_column='PhoneNo', max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'employeephones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('eid', models.CharField(db_column='Eid', max_length=255, primary_key=True, serialize=False)),
                ('fullname', models.CharField(db_column='FullName', max_length=255)),
                ('initname', models.CharField(db_column='InitName', max_length=255)),
                ('dob', models.DateField(db_column='DOB', null=True)),
                ('gender', models.CharField(db_column='Gender', max_length=50)),
                ('country', models.CharField(db_column='Country', max_length=100)),
                ('address', models.CharField(db_column='Address', max_length=500)),
                ('maritialstatus', models.CharField(db_column='MaritialStatus', max_length=50)),
                ('image', models.CharField(db_column='Image', max_length=1500)),
                ('designation', models.CharField(db_column='Designation', max_length=50)),
                ('status', models.CharField(db_column='Status', max_length=50)),
            ],
            options={
                'db_table': 'employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeTypes',
            fields=[
                ('etid', models.CharField(db_column='Etid', max_length=100, primary_key=True, serialize=False)),
                ('employeetype', models.CharField(db_column='EmployeeType', max_length=100)),
            ],
            options={
                'db_table': 'employeetypes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('email', models.CharField(db_column='Email', max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(db_column='Password', max_length=100)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserTypes',
            fields=[
                ('urid', models.CharField(db_column='Urid', max_length=100, primary_key=True, serialize=False)),
                ('usertype', models.CharField(db_column='UserType', max_length=100)),
            ],
            options={
                'db_table': 'usertypes',
                'managed': False,
            },
        ),
    ]
