# Generated by Django 4.2.11 on 2025-05-17 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_employeeeducation_employeeemails_employeephones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('eid', models.OneToOneField(db_column='Eid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='root.employees')),
                ('basicsalary', models.DecimalField(db_column='BasicSalary', decimal_places=2, max_digits=10)),
                ('internetchages', models.DecimalField(db_column='InterNetCharges', decimal_places=2, max_digits=10)),
                ('allowances', models.DecimalField(db_column='Allowances', decimal_places=2, max_digits=10)),
                ('deductions', models.DecimalField(db_column='Deductions', decimal_places=2, max_digits=10)),
                ('netsalary', models.DecimalField(db_column='NetSalary', decimal_places=2, max_digits=10)),
                ('bankaccountholdername', models.CharField(db_column='BankAccountHolderName', max_length=100, null=True)),
                ('bankaccno', models.CharField(db_column='BankAccNo', max_length=30, null=True)),
                ('bankname', models.CharField(db_column='BankName', max_length=100, null=True)),
                ('bankbranchname', models.CharField(db_column='BankBranchName', max_length=100, null=True)),
            ],
            options={
                'db_table': 'salary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SalaryPayments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('salary', models.DecimalField(db_column='Salary', decimal_places=2, max_digits=10)),
                ('paiddate', models.DateField(db_column='PaidDate')),
            ],
            options={
                'db_table': 'salarypayments',
                'managed': False,
            },
        ),
    ]
