# Generated by Django 4.2.11 on 2025-05-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_salary_salarypayments'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccountDetails',
            fields=[
                ('eid', models.CharField(db_column='Eid', max_length=100, primary_key=True, serialize=False)),
                ('bankaccountholdername', models.CharField(db_column='BankAccountHolderName', max_length=100, null=True)),
                ('bankaccno', models.CharField(db_column='BankAccNo', max_length=30, null=True)),
                ('bankname', models.CharField(db_column='BankName', max_length=100, null=True)),
                ('bankbranchname', models.CharField(db_column='BankBranchName', max_length=100, null=True)),
            ],
            options={
                'db_table': 'bankaccountdetails',
                'managed': False,
            },
        ),
    ]
