# Generated by Django 4.2.11 on 2025-05-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0004_bankaccountdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingBudget',
            fields=[
                ('eid', models.IntegerField(db_column='Eid', primary_key=True, serialize=False)),
                ('trainingbudgetrate', models.DecimalField(db_column='TrainingBudgetRate', decimal_places=2, max_digits=5, null=True)),
                ('trainingbudgetamount', models.DecimalField(db_column='TrainingBudgetAmount', decimal_places=2, max_digits=10, null=True)),
                ('remainingamount', models.DecimalField(db_column='RemainingAmount', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'trainingbudget',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrainingRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('eid', models.IntegerField(db_column='Eid', null=True)),
                ('requestedamount', models.DecimalField(db_column='RequestedAmount', decimal_places=2, max_digits=10, null=True)),
                ('reason', models.CharField(db_column='Reason', max_length=255, null=True)),
                ('applieddate', models.DateField(db_column='AppliedDate', null=True)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], db_column='Status', max_length=8, null=True)),
                ('granteddate', models.DateField(db_column='GrantedDate', null=True)),
                ('proofdocumenturl', models.CharField(db_column='ProofDocumentUrl', max_length=255, null=True)),
            ],
            options={
                'db_table': 'trainingrequest',
                'managed': False,
            },
        ),
    ]
