# Generated by Django 4.2.11 on 2025-06-05 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0005_trainingbudget_trainingrequest'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='trainingbudget',
            table='training',
        ),
        migrations.AlterModelTable(
            name='trainingrequest',
            table='trainingbudgetallocation',
        ),
    ]
