# Generated by Django 4.2.20 on 2025-06-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0006_alter_trainingbudget_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLeaveBalance',
            fields=[
                ('eid', models.CharField(db_column='Eid', max_length=255, primary_key=True, serialize=False)),
                ('totalannualleaves', models.IntegerField(db_column='TotalAnnualLeaves', null=True)),
                ('totalcasualleaves', models.IntegerField(db_column='TotalCasualLeaves', null=True)),
                ('annualleavebalance', models.IntegerField(db_column='AnnualLeaveBalance', null=True)),
                ('casualleavebalance', models.IntegerField(db_column='CasualLeaveBalance', null=True)),
            ],
            options={
                'db_table': 'employeeleavebalance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LeaveApplications',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('eid', models.CharField(db_column='Eid', max_length=255)),
                ('lid', models.CharField(db_column='Lid', max_length=10)),
                ('fromdate', models.DateField(db_column='FromDate', null=True)),
                ('todate', models.DateField(db_column='ToDate', null=True)),
                ('noofdays', models.IntegerField(db_column='NoOfDays', null=True)),
                ('description', models.TextField(db_column='Description', null=True)),
                ('applieddate', models.DateField(db_column='AppliedDate', null=True)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], db_column='Status', max_length=10, null=True)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], db_column='Priority', max_length=10, null=True)),
            ],
            options={
                'db_table': 'leaveapplications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('lid', models.CharField(db_column='Lid', max_length=10, primary_key=True, serialize=False)),
                ('leavetype', models.CharField(db_column='LeaveType', max_length=50)),
            ],
            options={
                'db_table': 'leavetype',
                'managed': False,
            },
        ),
    ]
